variables:
  prefix: $[format('0.{0:yyyy}.{0:MMdd}', pipeline.startTime)]
  version: $[format('{0}.{1}', variables.prefix, counter(variables.prefix, 1))] # e.g. 0.2001.0203.4
  fileVersion: $[variables.version]
  Codeql.Enabled: true

jobs:
  - job: buildJavaLibrarylinux
    displayName: Build Linux Java Library
    steps:
      # A combination of --batch-mode and --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      # options prevents spurious logging about downloading of Maven packages.
      - task: Maven@3
        displayName: Set library version
        inputs:
          mavenPomFile: java-library/pom.xml
          goals: versions:set
          options: --batch-mode --define=newVersion=$(version) --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --update-snapshots

      - task: Maven@3
        displayName: Build library
        inputs:
          mavenPomFile: java-library/pom.xml
          options: --batch-mode --define=org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --update-snapshots
