parameters:
  - name: fileVersion
    type: string
    default: "" # The file version of the extension to be built. This is set by the build pipeline.

jobs:
  - job: BuildExtension
    variables:
      fileVersion: ${{ parameters.fileVersion }}
    steps:
      - task: UseDotNet@2
        displayName: Acquire .NET 8.0 SDK
        inputs:
          packageType: sdk
          version: 8.0.x
          performMultiLevelLookup: true

      - task: NuGetAuthenticate@1
        displayName: Authenticate to CFS NuGet feed

      - task: DotNetCoreCLI@2
        displayName: Restore solution from CFS
        inputs:
          command: restore
          projects: extension/WebJobs.Extensions.RabbitMQ.sln
          feedsToUse: config
          nugetConfigPath: NuGet.config

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          workingDirectory: extension
          arguments: --no-restore --configuration Release -property:Version=$(fileVersion) -property:CommitHash=$(Build.SourceVersion)

      - task: DotNetCoreCLI@2
        displayName: Test extension
        inputs:
          command: test
          projects: |
            extension/WebJobs.Extensions.RabbitMQ.Tests/WebJobs.Extensions.RabbitMQ.Tests.csproj
          arguments: --no-restore --configuration Debug
