parameters:
  stageName: ""
  displayName: ""
  packageBaseName: ""
  packageVersion: ""
  relativeArtifactPath: ""
  blobPath: ""

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${ parameters.displayName }
    dependsOn: ValidateAndApprove
    condition: succeeded()
    jobs:
      - job: PublishJob
        displayName: Publish Package to Storage Account
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
            - input: pipelineArtifact
              pipeline: "_rabbitmq-extensionofficial"
              artifactName: "drop-extension"
              targetPath: "$(Pipeline.Workspace)/drop-extension"
            - input: pipelineArtifact
              pipeline: "_rabbitmq-extensionofficial"
              artifactName: "drop-java-library"
              targetPath: "$(Pipeline.Workspace)/drop-java-library"
        variables:
          - name: artifactPath
            value: "$(System.DefaultWorkingDirectory)/$(Release.PrimaryArtifactSourceAlias)/${{ parameters.artifactPath }}"
          - name: blobPath
            value: "${{ parameters.blobPath }}"
        steps:
          - task: PowerShell@2
            displayName: Show initialized variables
            inputs:
              targetType: inline
              script: |-
                Get-ChildItem env:
          - task: AzureFileCopy@6
            displayName: Upload .NET artifacts
            inputs:
              SourcePath: $(artifactPath)\*
              ConnectedServiceNameARM: azure-sdk-partner-drops
              Destination: AzureBlob
              StorageAccountRM: azuresdkpartnerdrops
              ContainerName: drops
              BlobPrefix: $(blobPath)
