parameters:
  stageName: ""
  displayName: ""
  artifactPath: "" # path from which package files are copied to the storage account
  blobPath: ""

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    dependsOn: ValidateAndApprove
    condition: succeeded()
    jobs:
      - job: PublishJob
        displayName: ${{ parameters.displayName }} to Storage Account
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
            - input: pipelineArtifact
              pipeline: "_rabbitmq-extensionofficial"
              artifactName: "drop-extension"
              targetPath: "$(Build.ArtifactStagingDirectory)\\drop-extension" # default download path for nuget artifact folder
            - input: pipelineArtifact
              pipeline: "_rabbitmq-extensionofficial"
              artifactName: "drop-java-library"
              targetPath: "$(Build.ArtifactStagingDirectory)\\drop-java-library" # default download path for maven artifact folder
        steps:
          - task: AzureFileCopy@6
            displayName: Upload .NET artifacts
            inputs:
              SourcePath: "${{ parameters.artifactPath }}/*"
              ConnectedServiceNameARM: azure-sdk-partner-drops
              Destination: AzureBlob
              StorageAccountRM: azuresdkpartnerdrops
              ContainerName: drops
              BlobPrefix: "${{ parameters.blobPath }}"
