jobs:
  - job: buildRabbitMQExtension
    displayName: Build RabbitMQ Extension
    templateContext:
      outputs:
        - output: pipelineArtifact
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: drop-extension
    steps:
      - ${{ if eq(variables.isTaggedBuild, 'True') }}:
          - powershell: | # Allow tags matching v1.2.3 and v1.2.3-xyz1
              $found = '$(Build.SourceBranchName)' | Select-String -Pattern '^v(((?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))(?:-\w+)?)$'
              if (-not $found) {
                Write-Error "Found unexpected tag name: $(Build.SourceBranchName)."
                exit 1
              }
              Write-Host "##vso[task.setvariable variable=version]$($found.Matches.Groups[1].Value)"
              Write-Host "##vso[task.setvariable variable=fileVersion]$($found.Matches.Groups[2].Value)"

            displayName: Extract version # e.g. 1.2.3

      # .NET Core 2.1 SDK is required by ESRP Code Signing tasks.
      - task: UseDotNet@2
        displayName: Acquire .NET Core 2.1 SDK
        inputs:
          packageType: sdk
          version: 2.1.x
          performMultiLevelLookup: true

      - task: UseDotNet@2
        displayName: Acquire .NET 8.0 SDK
        inputs:
          packageType: sdk
          version: 8.0.x
          performMultiLevelLookup: true

      - task: DotNetCoreCLI@2
        displayName: Build solution
        inputs:
          command: build
          workingDirectory: extension
          arguments: --configuration Release -property:Version=$(fileVersion) -property:CommitHash=$(Build.SourceVersion)

      - task: DotNetCoreCLI@2
        displayName: Test extension
        inputs:
          command: test
          workingDirectory: extension
          arguments: --configuration Debug

      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign extension assembly
          folderPath: extension/WebJobs.Extensions.RabbitMQ/bin/Release/netstandard2.0
          pattern: Microsoft.Azure.WebJobs.Extensions.RabbitMQ.dll
          signType: dll

      - task: DotNetCoreCLI@2
        displayName: Pack extension
        inputs:
          command: pack
          searchPatternPack: extension/WebJobs.Extensions.RabbitMQ/WebJobs.Extensions.RabbitMQ.csproj
          configurationToPack: Release
          buildProperties: Version=$(version);CommitHash=$(Build.SourceVersion)
          outputDir: $(Build.ArtifactStagingDirectory)/$(version)
          nobuild: true
          includesymbols: true
          verbosityPack: minimal

      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign extension package
          folderPath: $(Build.ArtifactStagingDirectory)/$(version)
          pattern: Microsoft.Azure.WebJobs.Extensions.RabbitMQ.*.nupkg
          signType: nuget

      - task: DeleteFiles@1
        displayName: Cleanup staging directory
        inputs:
          sourceFolder: $(Build.ArtifactStagingDirectory)/$(version)
          contents: CodeSignSummary-*.md

      - task: ManifestGeneratorTask@0
        displayName: Generate SBOM manifest
        inputs:
          buildDropPath: $(Build.ArtifactStagingDirectory)/$(version)
          packageName: Azure Functions RabbitMQ Extension
          packageVersion: $(version)
