trigger: none

parameters:
  - name: nugetPackageName
    type: string
    displayName: "Base name of the Nuget package"
    default: "Microsoft.Azure.WebJobs.Extensions.RabbitMQ"
  - name: mavenPackageName
    type: string
    displayName: "Base name of the Maven package"
    default: "azure-functions-java-library-rabbitmq"
  - name: packageVersion
    displayName: "Release version"
    type: string
    default: ""

resources:
  pipelines:
    - pipeline: "_rabbitmq-extensionofficial"
      project: "internal"
      source: 'azure\azure-functions-rabbitmq-extension\rabbitmq-extension.official'
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    stages:
      - stage: ValidateAndApprove
        displayName: Validate and Approve Release
        jobs:
          - template: /eng/cd/templates/predeployment/validate-nuget.yml@self
            parameters:
              nugetPackageBaseName: "${{ format('{0}.{1}', parameters.nugetPackageName, parameters.packageVersion) }}"
              nugetArtifactPath: "$(Build.ArtifactStagingDirectory)\\drop-extension"
              packageVersion: "${{ parameters.packageVersion }}"
          - template: /eng/cd/templates/predeployment/validate-maven.yml@self
            parameters:
              mavenPackageBaseName: "${{ format('{0}-{1}', parameters.mavenPackageName, parameters.packageVersion) }}"
              mavenArtifactPath: "$(Build.ArtifactStagingDirectory)\\drop-java-library"
              packageVersion: "${{ parameters.packageVersion }}"
          - template: /eng/cd/templates/predeployment/approve.yml@self
      - template: /eng/cd/templates/publish.yml@self
        parameters:
          stageName: "NugetPublishStage"
          displayName: "Publish Nuget Package"
          artifactPath: "$(Build.ArtifactStagingDirectory)\\drop-extension\\${{ parameters.packageVersion }}"
          blobPath: "azure-functions-rabbitmq-extension/net/${{ parameters.packageVersion }}"
      - template: /eng/cd/templates/publish.yml@self
        parameters:
          stageName: "MavenPublishStage"
          displayName: "Publish Maven Package"
          artifactPath: "$(Build.ArtifactStagingDirectory)\\drop-java-library\\${{ parameters.packageVersion }}"
          blobPath: "azure-functions-rabbitmq-extension/java/${{ parameters.packageVersion }}"
