trigger: none
variables:
  - template: /eng/cd/templates/release-variables.yml@self
resources:
  pipelines:
    - pipeline: "_rabbitmq-extensionofficial"
      project: "internal"
      source: 'azure\azure-functions-rabbitmq-extension\rabbitmq-extension.official'
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    stages:
      - stage: ValidateAndApprove
        displayName: Validate and Approve Release
        jobs:
          - template: templates/predeployment/validate-release.yml
            parameters:
              nugetPackageName: "$(nugetPackageName)"
              javaPackageName: "$(javaPackageName)"
              packageVersion: "$(packageVersion)"
          - template: templates/predeployment/approve-release.yml
      - template: templates/publish.yml
        parameters:
          stageName: "NugetPublishStage"
          displayName: "Publish Nuget Package"
          packageBaseName: "$(nugetPackageName)"
          packageVersion: "$(packageVersion)"
          relativeArtifactPath: "drop-extension/$(packageVersion)"
          blobPath: "azure-functions-rabbitmq-extension/net/$(packageVersion)"
      - template: templates/publish.yml
        parameters:
          stageName: "MavenPublishStage"
          displayName: "Publish Maven Package"
          packageBaseName: "$(javaPackageName)"
          packageVersion: "$(packageVersion)"
          relativeArtifactPath: "drop-java-library/$(packageVersion)"
          blobPath: "azure-functions-rabbitmq-extension/java/$(packageVersion)"
