variables:
  # It is a tagged build if it is triggered by pushing a tag.
  isTaggedBuild: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
  prefix: $[format('0.{0:yyyy}.{0:MMdd}', pipeline.startTime)]
  version: $[format('{0}.{1}', variables.prefix, counter(variables.prefix, 1))] # e.g. 0.2001.0203.4
  fileVersion: $[variables.version]
  Codeql.Enabled: true

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - dev
    always: true

trigger:
  branches:
    include:
      - dev
      - v*.x
  tags:
    include:
      - v*.*.*

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - /eng/ci/official-build.yml
      - /eng/ci/templates/official/**

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: 1es-pool-azfunc
        image: 1es-windows-2022
        os: windows
    stages:
      - stage: stage1
        displayName: Build Extension
        jobs:
          - template: /eng/ci/templates/official/build-extension.yml@self
          - template: /eng/ci/templates/official/build-java-library.yml@self
