pr:
  branches:
    include:
      - dev
      - v*.x

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - dev
    always: true

trigger:
  branches:
    include:
      - dev
      - v*.x

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  prefix: $[format('0.{0:yyyy}.{0:MMdd}', pipeline.startTime)]
  version: $[format('{0}.{1}', variables.prefix, counter(variables.prefix, 1))] # e.g. 0.2001.0203.4
  fileVersion: $[variables.version]
  Codeql.Enabled: true

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        compiled:
          enabled: true # still only runs for default branch
        runSourceLanguagesInSourceAnalysis: true

    stages:
      - stage: Build and Test Extension in Windows
        jobs:
          - template: /eng/ci/templates/build-test-extension.yml@self

      - stage: Build Java Library in Windows
        jobs:
          - template: /eng/ci/templates/build-java-library.yml@self
