<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Microsoft.Azure.WebJobs.Extensions.RabbitMQ.LangEndToEndTests</RootNamespace>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <NoWarn>$(NoWarn);CA1711;CA1822;xUnit1004</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Queues" Version="12.22.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="docker-compose.yml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="docker-compose.override.yml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="FunctionApps\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
